server:
  port: 1000

spring:
  profiles:
    active: dev
  jackson:
    time-zone: GMT+8
  data:
    redis:
      repositories:
        enabled: false
  datasource:
    hikari:
      connection-timeout: 400000
      idle-timeout: 600000
      max-lifetime: 1800000
      maximumPoolSize: 25
      minimum-idle: 5
    type: com.zaxxer.hikari.HikariDataSource
  #配置 Jpa
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    open-in-view: true

  redis:
    #数据库索引
    database: 0
    host: 127.0.0.1
    port: 6379
    password: 123456
    #连接超时时间
    timeout: 5000

#七牛云
qiniu:
  # 文件大小 /M
  max-size: 15

#验证码有效时间/分钟
code:
  expiration: 5